name: Update Schedule
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

permissions:
  contents: write
jobs:
  update-this-week:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Execute Python Script
        run: |
          cd docs/_data
          python3 update_this_week.py

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --exit-code || (git add -A && git commit -m "Update weekly schedule" -a)

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

  deploy-website:
    needs: update-this-week
    uses: ./.github/workflows/deploy.yml
